services:
  groq-llm-api:
    build: ./src/groq-llm-api
    ports:
      - "8080:8080"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}
    mem_limit: "1g" 
    restart: always
