global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Indique à Prometheus où trouver les fichiers de règles d'alerte
rule_files:
  - "rules/*.yml" # Charge tous les fichiers .yml dans le sous-répertoire 'rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'news_classifier_api'
    static_configs:
      - targets: ['news-classifier-api:8080']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'aiops-agent-monitor'
    static_configs:
      - targets: ['aiops-agent-monitor:8005']

