{
 "title": "API Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "News Classifier API Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"news_classifier_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Distribution by Category",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(category) (predictions_by_category_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency - /predict",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_request_duration_seconds_sum{endpoint=\"/predict\", method=\"POST\", status_code=\"200\"} / api_request_duration_seconds_count{endpoint=\"/predict\", method=\"POST\", status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency - /evaluate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_request_duration_seconds_sum{endpoint=\"/evaluate\", method=\"POST\"} / api_request_duration_seconds_count{endpoint=\"/evaluate\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(api_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(api_requests_total{status_code!=\"200\"}[1h]) / (rate(api_requests_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(endpoint, status_code) (api_requests_total)",
     "legendFormat": "{{endpoint}} = {{status_code}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(api_request_duration_seconds_bucket{endpoint=\"/predict\"}[1h])))",
     "legendFormat": "/predict"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (api_request_duration_seconds_bucket{endpoint=\"/evaluate\"}))",
     "legendFormat": "/evaluate"
    }
   ]
  }
 ]
}