apiVersion: 1
datasources:
  - name: 'Prometheus'
    type: prometheus
    uid: prometheus-datasource
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: 
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false